################################# Default configuration ###################
baseURL = "https://project-mori.github.io/"
title = "Project MORI"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "75"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
publishDir = "docs"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "background"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "project"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Works"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "team"
url = "#team"
weight = 5

# [[Languages.en.menu.main]]
# name = "pricing"
# url = "#pricing"
# weight = 5

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 4

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 6

# [[Languages.en.menu.main]]
# name = "themefisher"
# url = "https://themefisher.com/"
# weight = 8


################### Portugues Navigation ########################
[[Languages.pt.menu.main]]
name = "sobre"
url = "#about"
weight = 1

[[Languages.pt.menu.main]]
name = "serviços"
url = "#services"
weight = 2

[[Languages.pt.menu.main]]
name = "portfólio"
url = "#portfolio"
weight = 3

[[Languages.pt.menu.main]]
name = "equipe"
url = "#team"
weight = 4

[[Languages.pt.menu.main]]
name = "preços"
url = "#pricing"
weight = 5

[[Languages.pt.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.pt.menu.main]]
name = "contact"
url = "#contact"
weight = 7

# [[Languages.pt.menu.main]]
# name = "themefisher"
# url = "https://themefisher.com/"
# weight = 8


################### Japanese Navigation ########################
[[Languages.jp.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.jp.menu.main]]
name = "services"
url = "#services"
weight = 2

[[Languages.jp.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.jp.menu.main]]
name = "team"
url = "#team"
weight = 4

[[Languages.jp.menu.main]]
name = "pricing"
url = "#pricing"
weight = 5

[[Languages.jp.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.jp.menu.main]]
name = "contact"
url = "#contact"
weight = 7

# [[Languages.en.menu.main]]
# name = "themefisher"
# url = "https://themefisher.com/"
# weight = 8



############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "-15.459"
map_longitude = "-47.516"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "#"

# [[params.social]]
# icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
# link = "#"
#
# [[params.social]]
# icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
# link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

################################ Portugues Language ########################
[Languages.pt]
languageName = "Pt"
languageCode = "pt-BR"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

################################ Japanese Language ########################
[Languages.jp]
languageName = "Ja"
languageCode = "ja-ja"
contentDir = "content/japanese"
weight = 3
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
